class_name GatheringConfig
extends RefCounted

## Shared gathering balance values for worker resource trips.

const GATHER_WAIT_SECONDS: float = 1.0
const WORKER_CARRY_CAPACITY: int = 10
const GATHER_CHUNK_GOLD: int = 5
const GATHER_CHUNK_WOOD: int = 2
const TREE_STARTING_WOOD: int = 5000
const GOLD_MINE_STARTING_GOLD: int = 20000
const COMMAND_CENTER_DEPOSIT_REACH_BONUS: float = 0.75
const COMMAND_CENTER_DEPOSIT_EXTENDED_REACH: float = 3.0
const RESOURCE_INTERACTION_REACH_BONUS: float = 1.25
const MAX_GATHER_APPROACH_CANDIDATES: int = 16
const APPROACH_CANDIDATES_PER_RING: int = 8
const APPROACH_RING_STANDOFF_STEP: float = 0.75
const GATHER_APPROACH_BASE_SLOT_COUNT: int = 8
const GATHER_APPROACH_BASE_ANGLE_STEP: float = 45.0
const APPROACH_OCCUPIED_RADIUS: float = 1.1
const APPROACH_OCCUPIED_DESTINATION_RADIUS: float = 0.85
const APPROACH_OCCUPIED_MAX_ATTEMPTS: int = 8
const GATHER_STUCK_RECOVERY_DELAY: float = 2.5
const GATHER_STUCK_RECOVERY_COOLDOWN: float = 2.0
const GATHER_STUCK_MIN_MOVE_DISTANCE: float = 0.4
const TASK_CORNER_NUDGE_STUCK_DELAY: float = 0.35
const TASK_CORNER_NUDGE_DURATION: float = 0.65
const TASK_CORNER_NUDGE_DISTANCE: float = 1.8
const TASK_CORNER_NUDGE_STUCK_MOVE_RATIO: float = 0.15
const TASK_CORNER_NUDGE_MAX_SIDE_ATTEMPTS: int = 2
const TASK_REPATH_STUCK_DELAY: float = 1.25
const TASK_NAV_FINISH_TOLERANCE: float = 1.25
const TASK_STUCK_PROGRESS_RATIO: float = 0.2
const GATHER_LAST_RESORT_REACH_BONUS: float = 2.5
const WOOD_CHOP_REACH_BONUS: float = 0.65
const WOOD_CHOP_STANDOFF_EXTRA: float = 0.2
const AI_UNSTUCK_STUCK_DELAY: float = 2.0
const AI_UNSTUCK_COOLDOWN: float = 2.5
const AI_UNSTUCK_MIN_MOVE_DISTANCE: float = 0.35
const AI_UNSTUCK_NUDGE_MAX_TIME: float = 2.5
const AI_UNSTUCK_DIRECTION_COUNT: int = 10
const AI_UNSTUCK_DISTANCE_MIN: float = 3.0
const AI_UNSTUCK_DISTANCE_MAX: float = 6.0
const AI_UNSTUCK_ESCAPE_RESERVE_RADIUS: float = 1.25
const AI_UNSTUCK_RESERVE_SECONDS: float = 3.0
const AI_UNSTUCK_STAGGER_STEP: float = 0.15
const AI_UNSTUCK_STAGGER_MAX_DELAY: float = 0.6
const AI_UNSTUCK_CLUSTER_RADIUS: float = 4.0
const AI_UNSTUCK_CLEARANCE_DISTANCE: float = 2.0
const AI_UNSTUCK_REPEAT_LOCATION_RADIUS: float = 1.5
const AI_UNSTUCK_DISTANCE_REPEAT_SCALE: float = 1.35
const AI_UNSTUCK_BUILDING_SEARCH_RADIUS: float = 8.0
const AI_UNSTUCK_BUILDING_EDGE_PADDING: float = 0.35


static func get_gather_wait_seconds(speed_multiplier: float = 1.0) -> float:
	return GATHER_WAIT_SECONDS / maxf(speed_multiplier, 0.01)
