class_name GatheringConfig
extends RefCounted

## Shared gathering balance values for worker resource trips.

const GATHER_WAIT_SECONDS: float = 1.0
const WORKER_CARRY_CAPACITY: int = 10
const GATHER_CHUNK_GOLD: int = 5
const GATHER_CHUNK_WOOD: int = 2
const TREE_STARTING_WOOD: int = 100
const COMMAND_CENTER_DEPOSIT_REACH_BONUS: float = 0.75
const COMMAND_CENTER_DEPOSIT_EXTENDED_REACH: float = 3.0
const RESOURCE_INTERACTION_REACH_BONUS: float = 1.25
const MAX_GATHER_APPROACH_CANDIDATES: int = 16
const APPROACH_CANDIDATES_PER_RING: int = 8
const APPROACH_RING_STANDOFF_STEP: float = 0.75
const GATHER_APPROACH_BASE_SLOT_COUNT: int = 8
const GATHER_APPROACH_BASE_ANGLE_STEP: float = 45.0
const APPROACH_OCCUPIED_RADIUS: float = 1.1
const APPROACH_OCCUPIED_DESTINATION_RADIUS: float = 0.85
const APPROACH_OCCUPIED_MAX_ATTEMPTS: int = 8
const GATHER_STUCK_RECOVERY_DELAY: float = 2.5
const GATHER_STUCK_RECOVERY_COOLDOWN: float = 2.0
const GATHER_STUCK_MIN_MOVE_DISTANCE: float = 0.4
const TASK_CORNER_NUDGE_STUCK_DELAY: float = 0.35
const TASK_CORNER_NUDGE_DURATION: float = 0.65
const TASK_CORNER_NUDGE_DISTANCE: float = 1.8
const TASK_CORNER_NUDGE_STUCK_MOVE_RATIO: float = 0.15
const TASK_CORNER_NUDGE_MAX_SIDE_ATTEMPTS: int = 2
const TASK_REPATH_STUCK_DELAY: float = 1.25
const TASK_NAV_FINISH_TOLERANCE: float = 1.25
const TASK_STUCK_PROGRESS_RATIO: float = 0.2
const GATHER_LAST_RESORT_REACH_BONUS: float = 2.5
const WOOD_CHOP_REACH_BONUS: float = 0.65
const WOOD_CHOP_STANDOFF_EXTRA: float = 0.2
